### ISSUE TITLE
babel-plugin-istanbul no CSP compatibel

### ISSUE THREAD

**Issue by msteller-connyun** [istanbuljs/babel-plugin-istanbul#212]
Hey,

as soon I add the istanbul plugin to my babel configuration

```
      {
        test: /\.js$/,
        include: [/node_modules\/*\/src/, /src/],
        use: {
          loader: 'babel-loader',
           ...
            cacheDirectory: true,
            env: {
              test: {
                plugins: ['istanbul',]
              }
            }
          }
        }
      },
```

A `new Function` is added to the code:

```
  var global = new Function("return this")()
```

which violates our CSP rules.

**Comment by coreyfarrell** [comment]
This will ultimately be addressed via #208.  This will allow options `coverageGlobalScopeFunc: false, coverageGlobalScope: 'window'` - which should cause the instrumented code to set `global` as follows:
```js
var global = window
```

**Comment by praveen7557** [comment]
`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval'".` 

getting the above error because of `var global = new Function("return this")()`, anyway to solve this?

**Comment by just-toby** [comment]
`coverageGlobalScopeFunc: false, coverageGlobalScope: 'window'`

setting these options causes another babel plugin (`vanilla-extract`) to fail. does anyone know a workaround?
