### ISSUE TITLE
Coverage for all files using karma and includeAllSources: true

### ISSUE THREAD

**Issue by davidklassen** [istanbuljs/babel-plugin-istanbul#29]
Hello,

I'm using a setup with karma+jasmine+babelify for testing, my directory structure looks like this:

```
├── src
│   ├── moduleA.js
│   └── moduleB.js
└── test
    ├── config
    ├── functional
    └── unit
```

This is the karma.conf:

``` javascript
module.exports = (config) => {
    config.set({
        basePath: '../../',
        frameworks: ['browserify', 'jasmine'],
        files: [
            'test/unit/**/*.test.js',
        ],
        reporters: ['spec', 'coverage'],
        preprocessors: {
            'test/unit/**/*.test.js': ['browserify'],
        },
        browserify: {
            debug: true,
            transform: [['babelify', { plugins: ['istanbul'] }]],
        },
        coverageReporter: {
            dir: 'dist/coverage/unit',
            includeAllSources: true,
            reporters: [
                { type: 'html' },
                { type: 'json', file: 'coverage.json' },
            ],
        },
        browsers: ['PhantomJS'],
        singleRun: true,
    });
};
```

I'd like to make use of includeAllSources: true option for coverageReporter but can not find a way to have instrumentation for all files in src/ dir.

**Comment by jseminck** [comment]
We ran into the same issue. I found this issue on the karma-coverage github: https://github.com/karma-runner/karma-coverage/issues/125

Unfortunately this has not been resolved yet, but one user recommended the plugin https://www.npmjs.com/package/karma-coverage-allsources - this is working for us.

Give that one a try!

**Comment by sontek** [comment]
I just ran into this issue as well.  What is the process for getting it to work?  Should someone port the `karma-coverage-allsources` code?  It didn't work for me but some people seem to have success with it.

**Comment by wederch** [comment]
I circumvented this issue by creating a context.js which requires all files needed for the test. As you can see below it works with webpack.

context.js
```javascript
const testsContext = require.context('.', true, /spec\.js$/);
testsContext.keys().forEach(testsContext);

const componentsContext = require.context('../src/', true, /\.js$/);
componentsContext.keys().forEach(componentsContext);
```

karma.conf.js

```javascript
const webpackConfig = require('./webpack.config');

module.exports = function (config) {
  config.set({
    autoWatch: false,
    browsers: ['PhantomJS'],
    colors: true,
    coverageReporter: {
      includeAllSources: true,
      dir: 'build/reports/coverage',
      reporters: [
        {type: 'text'},
        {type: 'cobertura'}
      ]
    },
    files: [
      'test/context.js'
    ],
    frameworks: ['mocha', 'chai', 'sinon'],
    junitReporter: {
      outputDir: 'build/reports/test',
      outputFile: 'karma-junit-report.xml',
      useBrowserName: false
    },
    logLevel: config.LOG_INFO,
    port: 9876,
    preprocessors: {
      'test/context.js': ['webpack', 'sourcemap']
    },
    reporters: ['progress', 'dots', 'junit', 'coverage'],
    singleRun: true,
    webpack: {
      devtool: 'inline-source-map',
      module: {
        loaders: webpackConfig.module.loaders
      },
      postcss : webpackConfig.postcss,
      plugins : webpackConfig.plugins,
      externals: {
        'react/addons': true,
        'react/lib/ExecutionEnvironment': true,
        'react/lib/ReactContext': true
      }
    },
    webpackServer: {
      noInfo: true
    }
  });
};
```

I'm not completely happy with this solution but for now it works. If anyone has a cleaner solution I would be very interested in it (using a temporary npm package that was used to fix another issue is not a clean solution btw.)

**Comment by joyfulelement** [comment]
Same issue. But with `webpack` instead of `browserify` with the setup below.

I tried to use the `includeAllSources: true` flag in `coverageReporter` of `karma.conf.js`, however the generated output doesn't include the untested files. It appears that the similar problem could be solved with `isparta-loader` (https://github.com/karma-runner/karma-coverage/issues/192) though I was under the impression that `isparta-loader` package is deprecated in favor of `babel-plugin-istanbul`? 

What would be the proper setup for `babel-plugin-istanbul` in order to get the `includeAllSources` to work? Any suggestions would be appreciated.

Here is the `.babelrc`

```
{
  ...
  "env": {
    "test": {
      "plugins": [
        [
          "istanbul",
          {
            "exclude": [
              "**/__tests__/**"
            ]
          }
        ]
      ]
    }
  }
```

Here is the lineup of the libraries in `package.json`:

```
...
    "babel-plugin-istanbul": "2.0.0",
    "karma": "1.1.1",
    "karma-chrome-launcher": "1.0.1",
    "karma-cli": "1.0.1",
    "karma-coverage": "1.1.1",
    "karma-firefox-launcher": "1.0.0",
    "karma-jasmine": "1.0.2",
    "karma-sourcemap-loader": "0.3.7",
    "karma-spec-reporter": "0.0.26",
    "karma-webpack": "1.7.0",
    "webpack": "1.13.1",
...
```

Here is the code snippet from `karma.conf.js`:

```
config.set({
...
    preprocessors: {
      '../../src/js/**/*.js': [ 'webpack', 'sourcemap' ],
      '../../src/js/**/*.jsx': [ 'webpack', 'sourcemap' ],
      '../../src/js/**/__tests__/*spec.js': [ 'webpack', 'sourcemap' ],
      '../../src/js/**/__tests__/**/*spec.js': [ 'webpack', 'sourcemap' ]
    },

    webpack: {
      module: {
        loaders: [
          {
            test: /\.(js|jsx)$/,
            exclude: /node_modules/,
            loaders: [ 'babel-loader' ] //babel loads jsx and es6-7
          },
          { test: /\.json$/, loader: 'json-loader' }
        ]
      },
      plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
        new webpack.IgnorePlugin(/^fs$/)
      ],
      devtool: 'cheap-module-eval-source-map'
    },

    reporters: [ 'spec', 'coverage' ],

    coverageReporter: {
      reporters: [
        { type: 'html', dir: 'coverage/', subdir: 'report-html', includeAllSources: true },
        { type: 'cobertura', dir: 'coverage/report-cobertura/', file: 'cobertura.txt', includeAllSources: true },
        { type: 'text-summary', includeAllSources: true }
      ]
    },
...
})
```

**Comment by bcoe** [comment]
@joyfulelement we've added support for `--all` using `nyc`, would this work for this use-case?

https://github.com/istanbuljs/babel-plugin-istanbul/issues/4

**Comment by wezleytsai** [comment]
How would one use the `--all` flag through karma config?

**Comment by bcoe** [comment]
@wezleytsai @joyfulelement @sontek @davidklassen there's an approach outlined here, for covering all files using Karma:

https://github.com/istanbuljs/babel-plugin-istanbul/issues/105

For technologies other than Karma, there are various approaches to achieving coverage of untested files:

* nyc exposes a `--all` flag, which will result in all files being covered.
* babel-plugin-istanbul exposes an `onCover` hook which can also be used to track coverage for all files. @marco-ramirez's repo https://github.com/marco-ramirez/babel-plugin-istanbul-include-untested-example/blob/master/task/test.js#L13 provides a great example of how to do this.
  * I would love help adding more docs to https://istanbul.js.org/, outlining how to achieve `--all` functionality for various technologies.
  * it might be worth trying to generalize Marco's work somewhat; could we build this feature into test runners like `karma` so that there's less fiddling with config in `babel-plugin-istanbul`? CC: @dignifiedquire?
