### ISSUE TITLE
Not actually being used in bemuse project

### ISSUE THREAD

**Issue by ernsheong** [istanbuljs/babel-plugin-istanbul#39]
Bemuse project as specified in README doesn't actually use this plugin?

Looking for a real world working example with karma + webpack config.

**Comment by hzoo** [comment]
Bemuse is using https://github.com/dtinth/babel-plugin-__coverage__, which this project is based off of (the readme was copied over so might not be accurate like in this case)

**Comment by bcoe** [comment]
@ernsheong anything we should be doing on our end? perhaps open an issue on Bemuse?

**Comment by dtinth** [comment]
I plan to migrate to it :)

**Comment by dtinth** [comment]
https://github.com/bemusic/bemuse/pull/360

**Comment by bcoe** [comment]
@ernsheong @dtinth thanks for the update 👍 if you have any thoughts about potential tutorials we could write for karma + webpack, would love your thoughts:

http://istanbul.js.org/

https://github.com/istanbuljs/istanbuljs.github.io/issues/7

**Comment by dtinth** [comment]
Here’s some idea for the tutorials:

For browser-based tests, we need to ensure that:

- Put Babel with `babel-plugin-istanbul` at the right place.
- Configure the coverage plugin to take the coverage report, but not instrument the code.

For example,

## Karma + webpack

- `karma-webpack` uses `webpack` to bundle modules. Therefore, `babel-loader` should be used in webpack.
- Add `coverage` as `karma` reporter.
- Don’t add `coverage` as a preprocessor according Karma’s tutorial, because the file has already been instrumented during webpack phase.

## Plain Karma

- Use `karma-babel-preprocessor` with `babel-plugin-istanbul`.
- Add `coverage` as `karma` reporter.
- Don’t add `coverage` as a preprocessor according Karma’s tutorial, because the file has already been instrumented during babel phase.

---

Perhaps, we can also write an overview of how coverage measurement is done, where we can point each tutorial to, so that user understand how all of these work together. Here’s my draft:

> To successfully measure your test coverage requires three things:
>
> 1. The instrumenter that takes JavaScript code and injects instructions to record coverage data (“code coverage instrumentation”).
>
>   - Implemented in `istanbul-lib-instrument` and also available as babel plugin `babel-plugin-istanbul`.
>
>   - The instrumented code, when run, will produce a global variable `__coverage__` which contains the coverage data.
>
> 2. The reporter that takes the recorded coverage data and generate nice report.
>
>   - Implemented in `istanbul-reports`.
>
> 3. The tool that takes your code, runs it through your test framework, collects the coverage data once the test’s done, and finally pass the collected data to the reporter.
>
>   - Implemented in `nyc` for Node.js-based tests.
>
>   - Third-party modules available for browser-based tests: `karma-coverage`, `test-bed`.
>
>       - Some tools (test-bed) may not instrument your code (it expects you to instrument your code beforehand e.g. through `babel-plugin-istanbul`).
>
>       - Most tools can be configured not to instrument your code. This lets you use alternative instrumenter and lets you pre-instrument your code.
